### ISSUE TITLE
about the  video generation？

### ISSUE THREAD

**Issue by pupu-chenyanyan** [Len-Li/SyntheOcc#2]
Hello, thank you for your wonderful work, please ask where the video generation code for the second phase training of this project mentioned in the paper is? If possible, what about the relevant checkpoints? 
Thanks!

**Comment by Len-Li** [comment]
Hi, 

For video generation in cross-frame attention, we follow the standard training process in magicdrive-video. Please check out their code for details.

Besides, we are preparing a cogvideox video generation model. This will be more effective than newly-added cross-frame attention.

**Comment by begumaltunbas** [comment]
Hi, is there an estimated release date for your cogvideox model? Also thanks for your great work.

**Comment by Len-Li** [comment]
I will release the cogvideo code upon the paper's acceptance. Thank you!
